# This workflow builds a Docker image for a Flask app and pushes it to Quay.io with latest and version tags
name: Build and Push Flask Docker Image to Quay.io

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    # Checkout the code from the repository
    - name: Checkout Code
      uses: actions/checkout@v4

    # Log in to Quay.io using secrets
    - name: Log in to Quay.io
      uses: docker/login-action@v3
      with:
        registry: quay.io
        username: ${{ secrets.QUAY_USERNAME }}
        password: ${{ secrets.QUAY_PASSWORD }}

    # Set up Docker Buildx for building the image
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    # Get version number from VERSION file or fallback to default
    - name: Get version number
      id: get_version
      run: |
        if [ -f VERSION ]; then
          VERSION=$(cat VERSION)
        else
          VERSION="1.0.0"
        fi
        echo "VERSION=$VERSION" >> $GITHUB_ENV

    # Build and tag Docker images (latest and versioned)
    - name: Build Docker Images
      run: |
        IMAGE_NAME="business-rule-client"  # Change if needed

        # Build Docker image with both tags
        docker build -t quay.io/${{ secrets.QUAY_USERNAME }}/$IMAGE_NAME:latest \
                     -t quay.io/${{ secrets.QUAY_USERNAME }}/$IMAGE_NAME:$VERSION .

    # Push both Docker images to Quay.io
    - name: Push Docker Images to Quay.io
      run: |
        IMAGE_NAME="business-rule-client"

        # Push both tags
        docker push quay.io/${{ secrets.QUAY_USERNAME }}/$IMAGE_NAME:latest
        docker push quay.io/${{ secrets.QUAY_USERNAME }}/$IMAGE_NAME:$VERSION
